<a href="https://colab.research.google.com/github/fathimabasheerr/crop_recommendation_system/blob/main/crop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [174]:
import pandas as pd
import matplotlib as plt
import numpy as np


In [175]:
dataset=pd.read_csv("/content/Crop_recommendation.csv")

In [225]:
dataset.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [226]:
from sklearn.preprocessing import StandardScaler

In [227]:
scaler=StandardScaler()

In [228]:
scaler.fit(dataset.drop("label",axis=1))

StandardScaler()

In [229]:
dataset.columns[:-1]

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], dtype='object')

In [230]:
Scaler_feature=scaler.transform(dataset.drop("label",axis=1))

In [231]:
new_dataset=pd.DataFrame(Scaler_feature,columns=dataset.columns[:-1])

In [232]:
new_dataset

N         P         K  temperature  humidity        ph  rainfall
0     1.068797 -0.344551 -0.101688    -0.935587  0.472666  0.043302  1.810361
1     0.933329  0.140616 -0.141185    -0.759646  0.397051  0.734873  2.242058
2     0.255986  0.049647 -0.081939    -0.515898  0.486954  1.771510  2.921066
3     0.635298 -0.556811 -0.160933     0.172807  0.389805  0.660308  2.537048
4     0.743673 -0.344551 -0.121436    -1.083647  0.454792  1.497868  2.898373
...        ...       ...       ...          ...       ...       ...       ...
2195  1.529390 -0.587134 -0.318922     0.228814 -0.227709  0.401395  1.352437
2196  1.312641 -1.163269 -0.417666     0.355720 -0.666947 -0.494413  0.445183
2197  1.827421 -0.617457 -0.358420    -0.293218 -0.191235 -0.138120  1.271418
2198  1.800327 -0.647780 -0.279425     0.129612 -0.869518  0.373904  0.431545
2199  1.448109 -1.072300 -0.358420    -0.397667 -0.498020  0.401096  0.682005

[2200 rows x 7 columns]

In [184]:
from sklearn.model_selection import train_test_split


In [185]:
x = new_dataset
y = dataset['label']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,test_size=0.3)

In [186]:
y.shape

(2200,)

In [187]:
x.shape

(2200, 7)

KNN and naive

In [188]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
knn = KNeighborsClassifier(n_neighbors=47)
gnb = GaussianNB()
bnb = BernoulliNB()

knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=47)

In [189]:
gnb.fit(xtrain,ytrain)
bnb.fit(xtrain,ytrain)


BernoulliNB()

In [190]:
ypred = knn.predict(xtest)

In [191]:
gpred=gnb.predict(xtest)
bpred=bnb.predict(xtest)

In [192]:
from sklearn.metrics import classification_report,confusion_matrix

In [193]:
from sklearn.metrics import accuracy_score

In [236]:
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

[[34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0 20  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  6  0 11 14  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [195]:

print("Test data accuracy:",accuracy_score( ytest,ypred))

Test data accuracy: 0.8757575757575757


In [196]:
print(confusion_matrix(ytest,gpred))
print(classification_report(ytest,gpred))

[[34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 34  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [197]:
print("Test data accuracy:",accuracy_score( ytest,gpred))

Test data accuracy: 0.9939393939393939


In [198]:
print(confusion_matrix(ytest,bpred))
print(classification_report(ytest,bpred))

[[31  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0 24  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  1  0  0  3  0  0]
 [ 0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  2  0  0 13  0  0  0  0  0  0  0  0  3  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  1  9  0  0  4  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  4  0  1  0  0 18  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 27  5  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  0  0  0  0  0 12 16  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [237]:
print("Test data accuracy:",accuracy_score( ytest,bpred))

Test data accuracy: 0.7681818181818182


In [239]:
inputData = {"N" :62,
"P" :37,
"K" : 19,
"temperature" : 24.2547,
"humidity" : 64.742,
"ph" : 6.780,
"rainfall" : 104.2322
}

In [240]:
dataframe = pd.DataFrame([inputData])

In [241]:
dataframe

N   P   K  temperature  humidity    ph  rainfall
0  62  37  19      24.2547    64.742  6.78  104.2322

In [242]:
yprednew = knn.predict(dataframe)


In [204]:
scaler.fit(dataframe)
Scaler_feature=scaler.transform(dataframe)
new_dataset=pd.DataFrame(Scaler_feature)

In [243]:
print(yprednew)

['rice']


In [244]:
bprednew = bnb.predict(dataframe)

In [245]:
gprednew = gnb.predict(dataframe)

In [246]:
print(gprednew)

['pigeonpeas']


In [247]:
print(bprednew)

['papaya']


In [210]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [211]:
y_pred = clf.predict(xtest)
print("Train data accuracy:",accuracy_score(y_true = ytrain, y_pred=clf.predict(xtrain)))
print("Test data accuracy:",accuracy_score(y_true = ytest, y_pred=y_pred))

Train data accuracy: 1.0
Test data accuracy: 0.9863636363636363


svm


In [212]:
from sklearn import svm

In [213]:
clf2=svm.SVC(kernel='linear')
clf2.fit(xtrain,ytrain)

SVC(kernel='linear')

In [214]:
predsvm=clf2.predict(xtest)

In [215]:
print("Accuracy:", accuracy_score(ytest,predsvm))

Accuracy: 0.9742424242424242


In [248]:
prednew = clf2.predict(dataframe)

In [249]:
print(prednew)

['apple']
