<a href="https://colab.research.google.com/github/fathimabasheerr/crop_recommendation_system/blob/main/crop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!pwd

/content


In [4]:
dataset=pd.read_csv('/content/drive/MyDrive/dataset/Crop_recommendation.csv')

In [5]:
dataset

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [6]:
dataset.size

17600

In [7]:
dataset['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [8]:
dataset['label'].value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

In [9]:
new_data = pd.DataFrame([{'N':8,'P':23,'K':38,'temperature':19.30106297, 'humidity':87.1775172,'ph':7.005410734,'rainfall':105.4766591}])

In [10]:
data = dataset.append(new_data)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
data

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee
0       8  23  38    19.301063  87.177517  7.005411  105.476659     NaN

[2201 rows x 8 columns]

In [13]:
scaler=StandardScaler()

In [14]:
scaler.fit(data.drop("label",axis=1))

StandardScaler()

In [15]:
dataset.columns[:-1]

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], dtype='object')

In [16]:
Scaler_feature=scaler.transform(data.drop("label",axis=1))

In [17]:
new_dataset=pd.DataFrame(Scaler_feature,columns=data.columns[:-1])

In [18]:
new_dataset

N         P         K  temperature  humidity        ph  rainfall
0     1.069241 -0.344144 -0.101619    -0.934902  0.472400  0.042992  1.810755
1     0.933783  0.141039 -0.141124    -0.758984  0.396776  0.734645  2.242550
2     0.256491  0.050067 -0.081866    -0.515266  0.486689  1.771405  2.921712
3     0.635774 -0.556412 -0.160877     0.173352  0.389530  0.660071  2.537607
4     0.744141 -0.344144 -0.121372    -1.082944  0.454523  1.497730  2.899014
...        ...       ...       ...          ...       ...       ...       ...
2196  1.313067 -1.162891 -0.417666     0.356242 -0.667344 -0.494786  0.445267
2197  1.827809 -0.617060 -0.358407    -0.292615 -0.191577 -0.138451  1.271690
2198  1.800717 -0.647384 -0.279395     0.130163 -0.869938  0.373633  0.431626
2199  1.448525 -1.071919 -0.358407    -0.397050 -0.498397  0.400828  0.682143
2200 -1.152277 -0.920299 -0.200383    -1.246695  0.704909  0.692397  0.036628

[2201 rows x 7 columns]

In [19]:
predict = new_dataset[-1:]
print(predict)

             N         P         K  temperature  humidity        ph  rainfall
2200 -1.152277 -0.920299 -0.200383    -1.246695  0.704909  0.692397  0.036628


In [20]:
from sklearn.model_selection import train_test_split


In [21]:
x = new_dataset[:-1]
y = dataset['label']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,test_size=0.4)

In [22]:
y.shape

(2200,)

In [23]:
x.shape

(2200, 7)

KNN and naive

In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
knn = KNeighborsClassifier(n_neighbors=47)
gnb = GaussianNB()
bnb = BernoulliNB()

knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=47)

In [25]:
gnb.fit(xtrain,ytrain)
bnb.fit(xtrain,ytrain)


BernoulliNB()

In [26]:
ypred = knn.predict(xtest)

In [27]:
gpred=gnb.predict(xtest)
bpred=bnb.predict(xtest)

In [28]:
from sklearn.metrics import classification_report,confusion_matrix

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
# KNN accuracy
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

[[48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0 30  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  9  0 18 16  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [31]:

print("Test data accuracy:",accuracy_score( ytest,ypred))

Test data accuracy: 0.8590909090909091


In [32]:
#guassian accuracy score
print(confusion_matrix(ytest,gpred))
print(classification_report(ytest,gpred))

[[48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 41  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 41  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 47  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [33]:
print("Test data accuracy:",accuracy_score( ytest,gpred))

Test data accuracy: 0.9931818181818182


In [34]:
# bernoulli
print(confusion_matrix(ytest,bpred))
print(classification_report(ytest,bpred))

[[44  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0 34  0  0  0  0  0  0  0  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0  0  0  0  0  0  0  1  0  0  4  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 38  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  3  0  0 15  0  0  0  0  0  0  0  0  3  0  0 21  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  4 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  5  0  1  0  0 26  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 34  7  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  0  1  5  0 16 18  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [35]:
print("Test data accuracy:",accuracy_score( ytest,bpred))

Test data accuracy: 0.7670454545454546


In [36]:
xtest.head(1)

N         P         K  temperature  humidity        ph  rainfall
1451  1.36725 -1.102243 -0.022607     0.766435  1.044244 -0.367948 -1.404543

In [37]:
ytest.head(1)

1451    muskmelon
Name: label, dtype: object

In [38]:
knn.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype=object)

In [39]:
gnb.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype='<U11')

In [40]:
bnb.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype='<U11')

In [41]:
yprednew = knn.predict(predict)


In [42]:
#Prediction of KNN
print(yprednew)

['pomegranate']


In [43]:
bprednew = bnb.predict(predict)

In [44]:
gprednew = gnb.predict(predict)

In [45]:
#Prediction of GNB
print(gprednew)

['pomegranate']


In [46]:
#Prediction of BNB
print(bprednew)

['orange']


Decision Tree

In [47]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [48]:
y_pred = clf.predict(xtest)
print("Train data accuracy:",accuracy_score(y_true = ytrain, y_pred=clf.predict(xtrain)))
print("Test data accuracy:",accuracy_score(y_true = ytest, y_pred=y_pred))

Train data accuracy: 1.0
Test data accuracy: 0.9829545454545454


In [49]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        48
      banana       1.00      1.00      1.00        36
   blackgram       0.92      0.95      0.93        37
    chickpea       1.00      1.00      1.00        47
     coconut       1.00      1.00      1.00        43
      coffee       1.00      1.00      1.00        39
      cotton       1.00      1.00      1.00        40
      grapes       1.00      1.00      1.00        36
        jute       0.91      0.95      0.93        43
 kidneybeans       1.00      1.00      1.00        45
      lentil       0.90      1.00      0.95        37
       maize       1.00      1.00      1.00        37
       mango       1.00      1.00      1.00        41
   mothbeans       1.00      0.89      0.94        47
    mungbean       1.00      0.97      0.99        37
   muskmelon       1.00      1.00      1.00        35
      orange       1.00      1.00      1.00        35
      papaya       1.00    

In [50]:
tree = clf.predict(predict)

In [51]:
#Prediction of Decision tree
print(tree)

['pomegranate']


svm


In [52]:
from sklearn import svm

In [53]:
clf2=svm.SVC(kernel='linear')
clf2.fit(xtrain,ytrain)

SVC(kernel='linear')

In [54]:
predsvm=clf2.predict(xtest)

In [55]:
print("Accuracy:", accuracy_score(ytest,predsvm))

Accuracy: 0.9727272727272728


In [56]:
prednew = clf2.predict(predict)

In [57]:
#Prediction of SVM
print(prednew)

['pomegranate']


Logistic Regression

In [58]:
from sklearn.linear_model import LogisticRegression


In [59]:
log = LogisticRegression()
log.fit(xtrain, ytrain)

LogisticRegression()

In [60]:
logpred = log.predict(xtest)

In [61]:
print("Test data accuracy:",accuracy_score( ytest,logpred))

Test data accuracy: 0.9579545454545455


In [62]:
logs=log.predict(predict)

In [63]:
#prediction of logistic Regression
print(logs)

['pomegranate']


In [64]:
listsOfCropsFinal = []

listsOfCropsFinal.append(yprednew[0]) #knn
listsOfCropsFinal.append(gprednew[0]) #Gaussian
listsOfCropsFinal.append(bprednew[0]) #Bernoulli
listsOfCropsFinal.append(tree[0])     #Decision Tree
listsOfCropsFinal.append(prednew[0])  #Svm
listsOfCropsFinal.append(logs[0])     #logistic

In [65]:
listsOfCropsFinal

['pomegranate',
 'pomegranate',
 'orange',
 'pomegranate',
 'pomegranate',
 'pomegranate']

In [66]:
max_occurrences = []
for i in listsOfCropsFinal:
   countOfstring= listsOfCropsFinal.count(i)
   max_occurrences.append(countOfstring)
print(max_occurrences)
output = listsOfCropsFinal[max_occurrences.index(max(max_occurrences))]
print(output)

[5, 5, 1, 5, 5, 5]
pomegranate
