In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!pwd

/content


In [4]:
cd dataset/

[Errno 2] No such file or directory: 'dataset/'
/content


In [5]:
ls


drive/  sample_data/


In [6]:
dataset=pd.read_csv('/content/drive/MyDrive/dataset/Crop_recommendation.csv')

In [7]:
dataset

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler=StandardScaler()

In [10]:
scaler.fit(dataset.drop("label",axis=1))

StandardScaler()

In [11]:
dataset.columns[:-1]

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'], dtype='object')

In [12]:
Scaler_feature=scaler.transform(dataset.drop("label",axis=1))

In [13]:
new_dataset=pd.DataFrame(Scaler_feature,columns=dataset.columns[:-1])

In [14]:
new_dataset

N         P         K  temperature  humidity        ph  rainfall
0     1.068797 -0.344551 -0.101688    -0.935587  0.472666  0.043302  1.810361
1     0.933329  0.140616 -0.141185    -0.759646  0.397051  0.734873  2.242058
2     0.255986  0.049647 -0.081939    -0.515898  0.486954  1.771510  2.921066
3     0.635298 -0.556811 -0.160933     0.172807  0.389805  0.660308  2.537048
4     0.743673 -0.344551 -0.121436    -1.083647  0.454792  1.497868  2.898373
...        ...       ...       ...          ...       ...       ...       ...
2195  1.529390 -0.587134 -0.318922     0.228814 -0.227709  0.401395  1.352437
2196  1.312641 -1.163269 -0.417666     0.355720 -0.666947 -0.494413  0.445183
2197  1.827421 -0.617457 -0.358420    -0.293218 -0.191235 -0.138120  1.271418
2198  1.800327 -0.647780 -0.279425     0.129612 -0.869518  0.373904  0.431545
2199  1.448109 -1.072300 -0.358420    -0.397667 -0.498020  0.401096  0.682005

[2200 rows x 7 columns]

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
x = new_dataset
y = dataset['label']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,test_size=0.4)

In [36]:
y.shape

(2200,)

In [37]:
x.shape

(2200, 7)

KNN and naive

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
knn = KNeighborsClassifier(n_neighbors=47)
gnb = GaussianNB()
bnb = BernoulliNB()

knn.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=47)

In [22]:
gnb.fit(xtrain,ytrain)
bnb.fit(xtrain,ytrain)


BernoulliNB()

In [23]:
ypred = knn.predict(xtest)

In [24]:
gpred=gnb.predict(xtest)
bpred=bnb.predict(xtest)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
# KNN accuracy
print(confusion_matrix(ytest,ypred))
print(classification_report(ytest,ypred))

[[48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [12  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0 30  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  9  0 18 16  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [28]:

print("Test data accuracy:",accuracy_score( ytest,ypred))

Test data accuracy: 0.8590909090909091


In [29]:
#guassian accuracy score
print(confusion_matrix(ytest,gpred))
print(classification_report(ytest,gpred))

[[48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 43  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 41  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 41  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 47  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [30]:
print("Test data accuracy:",accuracy_score( ytest,gpred))

Test data accuracy: 0.9931818181818182


In [31]:
# bernoulli
print(confusion_matrix(ytest,bpred))
print(classification_report(ytest,bpred))

[[44  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0 34  0  0  0  0  0  0  0  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0  0  0  0  0  0  0  1  0  0  4  0  0]
 [ 0  0  0  0  0 39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 38  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  3  0  0 15  0  0  0  0  0  0  0  0  3  0  0 21  0]
 [ 0  0  0  0  0  0  0  0  0 45  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  4 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  5  0  1  0  0 26  0  0  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 34  7  0  0  0  0  0  0  0  0]
 [ 0  0  7  0  0  0  0  0  0  1  5  0 16 18  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [32]:
print("Test data accuracy:",accuracy_score( ytest,bpred))

Test data accuracy: 0.7670454545454546


In [17]:
xtest.head(1)

N         P         K  temperature  humidity       ph  rainfall
1451  1.366828 -1.102623 -0.022693     0.765964  1.044445 -0.36759 -1.404208

In [18]:
ytest.head(1)

1451    muskmelon
Name: label, dtype: object

In [33]:
knn.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype=object)

In [34]:
gnb.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype='<U11')

In [35]:
bnb.predict([[1.366828,-1.102623,0.022693,0.765964,1.044445,0.36759,-1.404208]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array(['muskmelon'], dtype='<U11')

In [38]:
inputData = {"N" :40,
"P" :11,
"K" : 44,
"temperature" : 24.45840036,
"humidity" : 86.10874614,
"ph" : 6.322396027,
"rainfall" : 111.3779693
}

In [41]:
dataframe = pd.DataFrame([inputData])

In [42]:
dataframe

N   P   K  temperature   humidity        ph    rainfall
0  40  11  44      24.4584  86.108746  6.322396  111.377969

In [43]:
yprednew = knn.predict(dataframe)


In [44]:
#Prediction of KNN
print(yprednew)

['rice']


In [45]:
bprednew = bnb.predict(dataframe)

In [46]:
gprednew = gnb.predict(dataframe)

In [47]:
#Prediction of GNB
print(gprednew)

['coffee']


In [48]:
#Prediction of BNB
print(bprednew)

['papaya']


Decision Tree

In [49]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [50]:
y_pred = clf.predict(xtest)
print("Train data accuracy:",accuracy_score(y_true = ytrain, y_pred=clf.predict(xtrain)))
print("Test data accuracy:",accuracy_score(y_true = ytest, y_pred=y_pred))

Train data accuracy: 1.0
Test data accuracy: 0.9818181818181818


In [51]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        48
      banana       1.00      1.00      1.00        36
   blackgram       0.92      0.95      0.93        37
    chickpea       1.00      1.00      1.00        47
     coconut       0.96      1.00      0.98        43
      coffee       1.00      1.00      1.00        39
      cotton       1.00      1.00      1.00        40
      grapes       1.00      1.00      1.00        36
        jute       0.89      0.95      0.92        43
 kidneybeans       1.00      1.00      1.00        45
      lentil       0.90      1.00      0.95        37
       maize       1.00      0.95      0.97        37
       mango       1.00      1.00      1.00        41
   mothbeans       1.00      0.89      0.94        47
    mungbean       1.00      1.00      1.00        37
   muskmelon       1.00      1.00      1.00        35
      orange       1.00      1.00      1.00        35
      papaya       1.00    

In [52]:
tree = clf.predict(dataframe)

In [53]:
crop_prediction = clf.predict([input])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [54]:
print(crop_prediction)

['apple']


In [55]:
#Prediction of Decision tree
print(tree)

['apple']


svm


In [56]:
from sklearn import svm

In [57]:
clf2=svm.SVC(kernel='linear')
clf2.fit(xtrain,ytrain)

SVC(kernel='linear')

In [58]:
predsvm=clf2.predict(xtest)

In [59]:
print("Accuracy:", accuracy_score(ytest,predsvm))

Accuracy: 0.9727272727272728


In [60]:
prednew = clf2.predict(dataframe)

In [61]:
#Prediction of SVM
print(prednew)

['apple']
